const fs = require('fs');
const p = '/data/pipeline/providers/video/svd.cjs';

const lines = [];
lines.push("'use strict';");
lines.push("");
lines.push("/**");
lines.push(" * providers/video/svd.cjs");
lines.push(" * Stable Video Diffusion (via Replicate) -- fallback tier for animation,");
lines.push(" * used by write-animator.js through providers/provider-router.cjs, behind");
lines.push(" * fal.ai Kling (the current sole/primary provider, hardcoded, no fallback");
lines.push(" * before this change -- see investigation report).");
lines.push(" *");
lines.push(" * generate({ sourceImagePath, animationStyle, outputPath }, providerConfig)");
lines.push(" *   -> { success: true, path, durationMs, provider: 'svd' }");
lines.push(" *   -> { success: false, statusCode, error }");
lines.push(" *");
lines.push(" * IMPORTANT capability gap, not fixable, flagged plainly: unlike Kling");
lines.push(" * (which accepts a text animationPrompt, see write-animator.js's");
lines.push(" * ANIMATION_DEFAULTS / shot.animationPrompt), Stable Video Diffusion is");
lines.push(" * image-conditioned only -- it has no text-prompt input at all. There is");
lines.push(" * no way to carry the channel's animation-style *wording* into this");
lines.push(" * fallback tier. The best available substitute is motion_bucket_id (an");
lines.push(" * integer motion-intensity dial), which this module derives from");
lines.push(" * animationStyle via a small heuristic map (ANIMATION_STYLE_TO_MOTION");
lines.push(" * below) -- documented as a judgment call, not a real equivalence.");
lines.push(" *");
lines.push(" * Model: christophy/stable-video-diffusion, version");
lines.push(" * 92a0c9a9cb1fd93ea0361d15e499dc879b35095077b2feed47315ccab4524036 --");
lines.push(" * confirmed live at investigation time (replicate.com/christophy/");
lines.push(" * stable-video-diffusion/versions). Chosen over the official");
lines.push(" * stability-ai/stable-video-diffusion because pricing/run-count/version");
lines.push(" * hash were concretely confirmed live for this one; flagging that the");
lines.push(" * official model (or CogVideoX, which the handoff also named -- and");
lines.push(" * which does accept a text prompt, unlike SVD) may be worth reconsidering");
lines.push(" * once real account access exists, given this model's low run count");
lines.push(" * (31.6K) and missing readme.");
lines.push(" * Input field names (input_image, video_length, sizing_strategy,");
lines.push(" * frames_per_second, motion_bucket_id, cond_aug, decoding_t) are this");
lines.push(" * family's long-stable, widely-documented Replicate schema -- confirmed");
lines.push(" * live via search results referencing this model's actual API reference");
lines.push(" * page, not a fresh predict.py fetch (repeated live fetches of cog-svd's");
lines.push(" * predict.py timed out in this sandbox). Output is a single mp4 URL.");
lines.push(" * Pricing confirmed live: ~$0.18/run on Nvidia L40S, varies by input;");
lines.push(" * \"predictions typically complete within 4 minutes\" per the model page --");
lines.push(" * MAX_WAIT_MS below is set generously longer than Kling's own budget to");
lines.push(" * account for that.");
lines.push(" */");
lines.push("");
lines.push("const fs = require('fs');");
lines.push("const https = require('https');");
lines.push("");
lines.push("const REPLICATE_API_TOKEN = process.env.REPLICATE_API_TOKEN;");
lines.push("const MODEL_VERSION = '92a0c9a9cb1fd93ea0361d15e499dc879b35095077b2feed47315ccab4524036';");
lines.push("const POLL_INTERVAL_MS = 3000;");
lines.push("const MAX_WAIT_MS = 300000; // README: \"predictions typically complete within 4 minutes\" -- generous margin");
lines.push("");
lines.push("// Overridable only for local testing (a mocked http server instead of");
lines.push("// api.replicate.com) -- never set in production.");
lines.push("const API_HOSTNAME = process.env.SVD_TEST_API_HOSTNAME || 'api.replicate.com';");
lines.push("const API_PORT = process.env.SVD_TEST_API_PORT ? Number(process.env.SVD_TEST_API_PORT) : 443;");
lines.push("const httpsOrHttp = process.env.SVD_TEST_API_PORT ? require('http') : https;");
lines.push("");
lines.push("// Judgment call (see header comment): SVD has no text-prompt input, so");
lines.push("// animationStyle can only steer motion intensity, not content/wording.");
lines.push("const ANIMATION_STYLE_TO_MOTION = {");
lines.push("  dramatic: 180,");
lines.push("  minimal: 100,");
lines.push("  'subtle-ken-burns': 40,");
lines.push("};");
lines.push("const DEFAULT_MOTION_BUCKET_ID = 127; // SVD's own documented default");
lines.push("");
lines.push("function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }");
lines.push("");
lines.push("function replicateRequest(method, reqPath, body) {");
lines.push("  return new Promise((resolve, reject) => {");
lines.push("    const payload = body ? JSON.stringify(body) : null;");
lines.push("    const options = {");
lines.push("      hostname: API_HOSTNAME,");
lines.push("      port: API_PORT,");
lines.push("      path: reqPath,");
lines.push("      method,");
lines.push("      headers: {");
lines.push("        'Authorization': `Bearer ${REPLICATE_API_TOKEN}`,");
lines.push("        'Content-Type': 'application/json',");
lines.push("        ...(payload ? { 'Content-Length': Buffer.byteLength(payload) } : {}),");
lines.push("      },");
lines.push("    };");
lines.push("    const req = httpsOrHttp.request(options, res => {");
lines.push("      let data = '';");
lines.push("      res.on('data', c => data += c);");
lines.push("      res.on('end', () => {");
lines.push("        let json;");
lines.push("        try { json = JSON.parse(data); } catch (e) {");
lines.push("          reject({ statusCode: res.statusCode, message: `Non-JSON response: ${e.message}` });");
lines.push("          return;");
lines.push("        }");
lines.push("        resolve({ statusCode: res.statusCode, body: json });");
lines.push("      });");
lines.push("    });");
lines.push("    req.on('error', err => reject({ statusCode: 0, message: err.message }));");
lines.push("    if (payload) req.write(payload);");
lines.push("    req.end();");
lines.push("  });");
lines.push("}");
lines.push("");
lines.push("function downloadFile(url, dest) {");
lines.push("  return new Promise((resolve, reject) => {");
lines.push("    const file = fs.createWriteStream(dest);");
lines.push("    httpsOrHttp.get(url, res => {");
lines.push("      res.pipe(file);");
lines.push("      file.on('finish', () => { file.close(); resolve(); });");
lines.push("    }).on('error', err => { fs.unlink(dest, () => {}); reject(err); });");
lines.push("  });");
lines.push("}");
lines.push("");
lines.push("function imageToDataUri(imagePath) {");
lines.push("  const ext = (imagePath.split('.').pop() || 'png').toLowerCase();");
lines.push("  const mime = ext === 'jpg' || ext === 'jpeg' ? 'image/jpeg' : 'image/png';");
lines.push("  const b64 = fs.readFileSync(imagePath).toString('base64');");
lines.push("  return `data:${mime};base64,${b64}`;");
lines.push("}");
lines.push("");
lines.push("async function generate({ sourceImagePath, animationStyle, outputPath }) {");
lines.push("  const startedAt = Date.now();");
lines.push("");
lines.push("  if (!REPLICATE_API_TOKEN) {");
lines.push("    return { success: false, statusCode: 401, error: 'REPLICATE_API_TOKEN not set' };");
lines.push("  }");
lines.push("  if (!sourceImagePath || !fs.existsSync(sourceImagePath)) {");
lines.push("    return { success: false, statusCode: 422, error: `svd requires an existing sourceImagePath (got: ${sourceImagePath})` };");
lines.push("  }");
lines.push("");
lines.push("  const motionBucketId = ANIMATION_STYLE_TO_MOTION[animationStyle] ?? DEFAULT_MOTION_BUCKET_ID;");
lines.push("");
lines.push("  try {");
lines.push("    const inputImage = imageToDataUri(sourceImagePath);");
lines.push("");
lines.push("    const create = await replicateRequest('POST', '/v1/predictions', {");
lines.push("      version: MODEL_VERSION,");
lines.push("      input: {");
lines.push("        input_image: inputImage,");
lines.push("        video_length: '14_frames_with_svd',");
lines.push("        sizing_strategy: 'maintain_aspect_ratio',");
lines.push("        frames_per_second: 6,");
lines.push("        motion_bucket_id: motionBucketId,");
lines.push("        cond_aug: 0.02,");
lines.push("        decoding_t: 7,");
lines.push("      },");
lines.push("    });");
lines.push("");
lines.push("    if (create.statusCode >= 400) {");
lines.push("      return {");
lines.push("        success: false,");
lines.push("        statusCode: create.statusCode,");
lines.push("        error: (create.body && (create.body.detail || create.body.title)) || `Replicate returned HTTP ${create.statusCode}`,");
lines.push("      };");
lines.push("    }");
lines.push("");
lines.push("    const predictionId = create.body.id;");
lines.push("    let prediction = create.body;");
lines.push("    const deadline = Date.now() + MAX_WAIT_MS;");
lines.push("");
lines.push("    while (prediction.status === 'starting' || prediction.status === 'processing') {");
lines.push("      if (Date.now() > deadline) {");
lines.push("        return { success: false, statusCode: 0, error: `svd prediction ${predictionId} timed out after ${MAX_WAIT_MS}ms` };");
lines.push("      }");
lines.push("      await sleep(POLL_INTERVAL_MS);");
lines.push("      const poll = await replicateRequest('GET', `/v1/predictions/${predictionId}`);");
lines.push("      if (poll.statusCode >= 400) {");
lines.push("        return { success: false, statusCode: poll.statusCode, error: `Poll failed: HTTP ${poll.statusCode}` };");
lines.push("      }");
lines.push("      prediction = poll.body;");
lines.push("    }");
lines.push("");
lines.push("    if (prediction.status !== 'succeeded') {");
lines.push("      return {");
lines.push("        success: false,");
lines.push("        statusCode: 500,");
lines.push("        error: (prediction.error && String(prediction.error)) || `Prediction ended with status \"${prediction.status}\"`,");
lines.push("      };");
lines.push("    }");
lines.push("");
lines.push("    const outputUrl = Array.isArray(prediction.output) ? prediction.output[0] : prediction.output;");
lines.push("    if (!outputUrl) {");
lines.push("      return { success: false, statusCode: 500, error: 'Prediction succeeded but returned no output URL' };");
lines.push("    }");
lines.push("");
lines.push("    await downloadFile(outputUrl, outputPath);");
lines.push("");
lines.push("    return {");
lines.push("      success: true,");
lines.push("      path: outputPath,");
lines.push("      provider: 'svd',");
lines.push("      durationMs: Date.now() - startedAt,");
lines.push("    };");
lines.push("  } catch (err) {");
lines.push("    const statusCode = (err && typeof err.statusCode === 'number') ? err.statusCode : 0;");
lines.push("    const message = (err && err.message) || String(err);");
lines.push("    return { success: false, statusCode, error: message };");
lines.push("  }");
lines.push("}");
lines.push("");
lines.push("module.exports = { generate };");
lines.push("");

const content = lines.join('\n');
fs.writeFileSync(p, content, 'utf8');
console.log('svd.cjs written — lines: ' + content.split('\n').length);
