const fs = require('fs');
const p = '/data/pipeline/providers/image/sdxl.cjs';

const lines = [];
lines.push("'use strict';");
lines.push("");
lines.push("/**");
lines.push(" * providers/image/sdxl.cjs");
lines.push(" * Stable Diffusion XL (via Replicate) -- fallback tier for image generation,");
lines.push(" * used by write-image-generator.js through providers/provider-router.cjs.");
lines.push(" *");
lines.push(" * generate({ prompt, negativePrompt, width, height, outputPath }, providerConfig)");
lines.push(" *   -> { success: true, path, durationMs, provider: 'sdxl' }");
lines.push(" *   -> { success: false, statusCode, error }");
lines.push(" * (provider-router.cjs's generic contract -- see that file's header.)");
lines.push(" *");
lines.push(" * Model: stability-ai/sdxl, version");
lines.push(" * a00d0b7dcbb9c3fbb34ba87d2d5b46c56969c84a628bf778a7fdaec30b1b99c5 --");
lines.push(" * confirmed live at investigation time (replicate.com/stability-ai/sdxl/");
lines.push(" * versions). Input field names/defaults (prompt, negative_prompt, width,");
lines.push(" * height, num_inference_steps, guidance_scale, scheduler, refine,");
lines.push(" * apply_watermark) are this model's long-stable, extremely widely");
lines.push(" * documented Replicate API surface -- confirmed live for model identity,");
lines.push(" * version hash, pricing, and run count; the full field list is");
lines.push(" * well-established public documentation for this specific mature model,");
lines.push(" * not a fresh predict.py fetch (repeated live fetches of cog-sdxl's actual");
lines.push(" * predict.py timed out in this sandbox -- flagging that distinction");
lines.push(" * plainly rather than presenting it as independently re-verified).");
lines.push(" * Pricing confirmed live: ~$0.0043/run on Nvidia L40S, varies by input.");
lines.push(" * Output is an array of image URLs (first element used here, num_outputs=1).");
lines.push(" */");
lines.push("");
lines.push("const fs = require('fs');");
lines.push("const https = require('https');");
lines.push("");
lines.push("const REPLICATE_API_TOKEN = process.env.REPLICATE_API_TOKEN;");
lines.push("const MODEL_VERSION = 'a00d0b7dcbb9c3fbb34ba87d2d5b46c56969c84a628bf778a7fdaec30b1b99c5';");
lines.push("const POLL_INTERVAL_MS = 2000;");
lines.push("const MAX_WAIT_MS = 120000;");
lines.push("");
lines.push("// Overridable only for local testing (a mocked http server instead of");
lines.push("// api.replicate.com) -- never set in production.");
lines.push("const API_HOSTNAME = process.env.SDXL_TEST_API_HOSTNAME || 'api.replicate.com';");
lines.push("const API_PORT = process.env.SDXL_TEST_API_PORT ? Number(process.env.SDXL_TEST_API_PORT) : 443;");
lines.push("const httpsOrHttp = process.env.SDXL_TEST_API_PORT ? require('http') : https;");
lines.push("");
lines.push("function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }");
lines.push("");
lines.push("function replicateRequest(method, reqPath, body) {");
lines.push("  return new Promise((resolve, reject) => {");
lines.push("    const payload = body ? JSON.stringify(body) : null;");
lines.push("    const options = {");
lines.push("      hostname: API_HOSTNAME,");
lines.push("      port: API_PORT,");
lines.push("      path: reqPath,");
lines.push("      method,");
lines.push("      headers: {");
lines.push("        'Authorization': `Bearer ${REPLICATE_API_TOKEN}`,");
lines.push("        'Content-Type': 'application/json',");
lines.push("        ...(payload ? { 'Content-Length': Buffer.byteLength(payload) } : {}),");
lines.push("      },");
lines.push("    };");
lines.push("    const req = httpsOrHttp.request(options, res => {");
lines.push("      let data = '';");
lines.push("      res.on('data', c => data += c);");
lines.push("      res.on('end', () => {");
lines.push("        let json;");
lines.push("        try { json = JSON.parse(data); } catch (e) {");
lines.push("          reject({ statusCode: res.statusCode, message: `Non-JSON response: ${e.message}` });");
lines.push("          return;");
lines.push("        }");
lines.push("        resolve({ statusCode: res.statusCode, body: json });");
lines.push("      });");
lines.push("    });");
lines.push("    req.on('error', err => reject({ statusCode: 0, message: err.message }));");
lines.push("    if (payload) req.write(payload);");
lines.push("    req.end();");
lines.push("  });");
lines.push("}");
lines.push("");
lines.push("function downloadFile(url, dest) {");
lines.push("  return new Promise((resolve, reject) => {");
lines.push("    const file = fs.createWriteStream(dest);");
lines.push("    httpsOrHttp.get(url, res => {");
lines.push("      res.pipe(file);");
lines.push("      file.on('finish', () => { file.close(); resolve(); });");
lines.push("    }).on('error', err => { fs.unlink(dest, () => {}); reject(err); });");
lines.push("  });");
lines.push("}");
lines.push("");
lines.push("async function generate({ prompt, negativePrompt, width, height, outputPath }) {");
lines.push("  const startedAt = Date.now();");
lines.push("");
lines.push("  if (!REPLICATE_API_TOKEN) {");
lines.push("    return { success: false, statusCode: 401, error: 'REPLICATE_API_TOKEN not set' };");
lines.push("  }");
lines.push("  if (!prompt) {");
lines.push("    return { success: false, statusCode: 422, error: 'sdxl requires a prompt' };");
lines.push("  }");
lines.push("");
lines.push("  try {");
lines.push("    const create = await replicateRequest('POST', '/v1/predictions', {");
lines.push("      version: MODEL_VERSION,");
lines.push("      input: {");
lines.push("        prompt,");
lines.push("        negative_prompt: negativePrompt || '',");
lines.push("        width: width || 1536,");
lines.push("        height: height || 1024,");
lines.push("        num_outputs: 1,");
lines.push("        scheduler: 'K_EULER',");
lines.push("        num_inference_steps: 50,");
lines.push("        guidance_scale: 7.5,");
lines.push("        refine: 'no_refiner',");
lines.push("        apply_watermark: false,");
lines.push("      },");
lines.push("    });");
lines.push("");
lines.push("    if (create.statusCode >= 400) {");
lines.push("      return {");
lines.push("        success: false,");
lines.push("        statusCode: create.statusCode,");
lines.push("        error: (create.body && (create.body.detail || create.body.title)) || `Replicate returned HTTP ${create.statusCode}`,");
lines.push("      };");
lines.push("    }");
lines.push("");
lines.push("    const predictionId = create.body.id;");
lines.push("    let prediction = create.body;");
lines.push("    const deadline = Date.now() + MAX_WAIT_MS;");
lines.push("");
lines.push("    while (prediction.status === 'starting' || prediction.status === 'processing') {");
lines.push("      if (Date.now() > deadline) {");
lines.push("        return { success: false, statusCode: 0, error: `sdxl prediction ${predictionId} timed out after ${MAX_WAIT_MS}ms` };");
lines.push("      }");
lines.push("      await sleep(POLL_INTERVAL_MS);");
lines.push("      const poll = await replicateRequest('GET', `/v1/predictions/${predictionId}`);");
lines.push("      if (poll.statusCode >= 400) {");
lines.push("        return { success: false, statusCode: poll.statusCode, error: `Poll failed: HTTP ${poll.statusCode}` };");
lines.push("      }");
lines.push("      prediction = poll.body;");
lines.push("    }");
lines.push("");
lines.push("    if (prediction.status !== 'succeeded') {");
lines.push("      return {");
lines.push("        success: false,");
lines.push("        statusCode: 500,");
lines.push("        error: (prediction.error && String(prediction.error)) || `Prediction ended with status \"${prediction.status}\"`,");
lines.push("      };");
lines.push("    }");
lines.push("");
lines.push("    const outputUrl = Array.isArray(prediction.output) ? prediction.output[0] : prediction.output;");
lines.push("    if (!outputUrl) {");
lines.push("      return { success: false, statusCode: 500, error: 'Prediction succeeded but returned no output URL' };");
lines.push("    }");
lines.push("");
lines.push("    await downloadFile(outputUrl, outputPath);");
lines.push("");
lines.push("    return {");
lines.push("      success: true,");
lines.push("      path: outputPath,");
lines.push("      provider: 'sdxl',");
lines.push("      durationMs: Date.now() - startedAt,");
lines.push("    };");
lines.push("  } catch (err) {");
lines.push("    const statusCode = (err && typeof err.statusCode === 'number') ? err.statusCode : 0;");
lines.push("    const message = (err && err.message) || String(err);");
lines.push("    return { success: false, statusCode, error: message };");
lines.push("  }");
lines.push("}");
lines.push("");
lines.push("module.exports = { generate };");
lines.push("");

const content = lines.join('\n');
fs.writeFileSync(p, content, 'utf8');
console.log('sdxl.cjs written — lines: ' + content.split('\n').length);
