'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const pkg=path.resolve(__dirname,'../..'), cand=path.join(pkg,'candidate'), wf=path.resolve(pkg,'..');
const v3=path.join(wf,'phase3-consolidated-act5-production-candidate-20261004-v3');
const candidateId='phase3-act5-approved-decisions-consolidated-20261004-v2';
const H={
v3:'af4b943d7d7b77fdf12d900f3e603ffcdd9083684a74a05a6d7d3c2e142c58ea',
outerV3:'d832bceccce0cf215fe90a4f4e45c40d1bd3bc1120c9afaafa7a8ecaddd392e0',
b009Amend:'f6f50f516f89ed9f27724e994e890cde65513747054a40f16360a9dc1eb46ba8',
b009Approval:'6d3e88e24a23777baa38da3325d9fb81f833943fb8b2a8eb6b106b2ce27c516f',
b015Visual:'76a7fef0ffc0ebe0f93d763395c1f667d87f78798f0f5c160b770e2a5c18773f',
b015Timing:'ece9be52468fdd5c73882736c28f4c4acb2bed44c7662a9494ef0aeded29a909',
b015Docket:'25637237930348da8d31ba1137ec7ca2f9df44de000343ce96dc84b6463f2c88',
b016Approval:'e33dc2bac466deac2a1807994064d61e64d4189a56fce5f5b60165c2520f2703',
b030Renewal:'2db259b6ddfd8770e172056603192ec7d88f5fab4e8f8b37f537b6ca015c3373',
b030Application:'e4d93e08935ebdf1f84a6e532a2a39a736a261f92cfa338ace7fe84354aa742b',
b030Lineage:'74e3e93449c187a8b22fbb2f96031e83db338c2d81cd69ae272bc0c3934850bf',
};
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const write=(p,o)=>fs.writeFileSync(p,JSON.stringify(o,null,2)+'\n');
const dig=p=>sha(fs.readFileSync(p));
const eq=(p,h,label)=>{if(dig(p)!==h)throw Error(label+'_HASH_MISMATCH:'+dig(p));};
function walk(dir,root=dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(d=>{const p=path.join(dir,d.name);if(d.isSymbolicLink())throw Error('SYMLINK:'+p);if(d.isDirectory())return walk(p,root);if(!d.isFile())throw Error('NON_FILE:'+p);return[{path:path.relative(root,p).split(path.sep).join('/'),full:p}];});}
function deepSet(o,key,val){if(!o||typeof o!=='object')return;if(Object.hasOwn(o,key))o[key]=val;for(const v of Object.values(o))if(v&&typeof v==='object')deepSet(v,key,val);}
function main(){
const temp=process.argv[2], secondTemp=process.argv[3];if(!temp||!secondTemp)throw Error('TWO_COMPILED_DIRS_REQUIRED');
eq(path.join(v3,'candidate','candidate-package-sha256.json'),H.v3,'V3_CANDIDATE_INDEX');eq(path.join(v3,'package-index.v1.json'),H.outerV3,'V3_OUTER_INDEX');
const pidx=read(path.join(v3,'candidate','candidate-package-sha256.json'));const outer3=read(path.join(v3,'package-index.v1.json'));if(outer3.candidateIndexSha256!==H.v3)throw Error('V3_BINDING_MISMATCH');
const outNames=['ACT5_B009__g00.svg','ACT5_B009__g00.png','ACT5_B015__g00.svg','ACT5_B015__g00.png'];
const bytes={};for(const n of outNames)bytes[n]=fs.readFileSync(path.join(temp,n));
const details=read(path.join(temp,'build-details.json'));
for(const n of outNames){const d=details.outputs.find(x=>x.path===n);if(d&&(d.bytes!==bytes[n].length||d.sha256!==sha(bytes[n])))throw Error('BUILD_OUTPUT_MISMATCH:'+n);const second=fs.readFileSync(path.join(secondTemp,n));if(second.length!==bytes[n].length||sha(second)!==sha(bytes[n]))throw Error('INDEPENDENT_BUILD_MISMATCH:'+n);}
const cpath=(...x)=>path.join(cand,...x), mkdir=p=>fs.mkdirSync(p,{recursive:true});
// The prior rejected B015 artwork remains in the immutable v3 parent. Bind
// the B016 exclusion to that source package explicitly; the v4 path now names
// the newly compiled, still-unapproved B015 output.
const b016DependencyPath=cpath('production-dependencies','act5-b016-deferred-b015-source.v1.json');
const b016Dependency=read(b016DependencyPath);
b016Dependency.excludedSource.parentCandidateId='phase3-act5-approved-decisions-consolidated-20261004-v1';
b016Dependency.excludedSource.parentPackagePath='../phase3-consolidated-act5-production-candidate-20261004-v3/candidate/assets/graphics/ACT5_B015__g00.svg';
write(b016DependencyPath,b016Dependency);
const shotsBytes=fs.readFileSync(cpath('shot-definitions.json')), shots=JSON.parse(shotsBytes), sMap=new Map(shots.allShots.map(x=>[x.shotId,x]));
const pmPath=cpath('production-manifest.json'),pm=read(pmPath), pmMap=new Map(pm.shots.map(x=>[x.shotId,x]));
const parentPm=read(path.join(v3,'candidate','production-manifest.json'));
const parentB030=parentPm.shots.find(x=>x.shotId==='ACT1_B030'),currentB030=pmMap.get('ACT1_B030');
if(!parentB030||!currentB030||JSON.stringify(parentB030)!==JSON.stringify(currentB030))throw Error('B030_SEMANTIC_OR_OBLIGATION_CHANGE');
const controlledRows=pm.shots.filter(x=>x.productionMethod==='CONTROLLED_STILL');
if(controlledRows.length!==34||controlledRows.some(x=>x.assetType!=='controlled_image'))throw Error('CONTROLLED_STILL_CLOSURE_MISMATCH');
const editPlan=read(cpath('edit-plan.json'));const b015Plan=editPlan.sequences.flatMap(s=>s.beats||[]).find(x=>x.beatId==='ACT5_B015');
if(!b015Plan||b015Plan.startSec!==571.9558705585937||b015Plan.endSec!==577.515875746582||b015Plan.durationSec!==5.560005187988281)throw Error('B015_EDIT_PLAN_TIMING_MISMATCH');
const s009=sMap.get('ACT5_B009'),s015=sMap.get('ACT5_B015');if(!s009||!s015)throw Error('SHOT_MISSING');
if(s015.startSec!==571.9558705585937||s015.endSec!==577.515875746582||s015.durationSec!==5.560005187988281)throw Error('B015_TIMING_MISMATCH');
const m009=pmMap.get('ACT5_B009'),m015=pmMap.get('ACT5_B015');if(m009.productionMethod!=='GRAPHIC_COMPILATION'||m009.assetType!=='graphic_compilation'||m015.productionMethod!=='GRAPHIC_COMPILATION')throw Error('PRODUCTION_CONTRACT_MISMATCH');
m009.graphicStatus='COMPLETE';m009.status='APPROVED';m009.blockerCodes=[];
const methods=['ESSENTIAL_ANIMATION','CONTROLLED_STILL','GENERATED_STILL','EVIDENCE_REFERENCE','GRAPHIC_COMPILATION'];
pm.methodCounts=Object.fromEntries(methods.map(k=>[k,pm.shots.filter(x=>x.productionMethod===k).length]));
pm.graphicSummary={primaryGraphicAssetShots:pm.shots.filter(x=>x.productionMethod==='GRAPHIC_COMPILATION').length,overlayGraphicShots:pm.shots.filter(x=>x.overlayGraphicRequirement===true).length,graphicBearingBeats:pm.shots.filter(x=>x.graphicObjectCount>0).length,graphicObjectCount:pm.shots.reduce((n,x)=>n+(Number.isInteger(x.graphicObjectCount)?x.graphicObjectCount:0),0),multiObjectBeatCount:pm.shots.filter(x=>x.graphicObjectCount>1).length};
pm.baseImageCount=pm.shots.filter(x=>['ESSENTIAL_ANIMATION','CONTROLLED_STILL','GENERATED_STILL'].includes(x.productionMethod)).length;pm.animationCallCount=pm.shots.filter(x=>x.productionMethod==='ESSENTIAL_ANIMATION').length;
write(pmPath,pm);const pmSha=dig(pmPath),shotsSha=sha(shotsBytes);
const graphicsDir=cpath('assets','graphics'), outDir=cpath('outputs','graphics');mkdir(graphicsDir);mkdir(outDir);
const targets=[
['assets/graphics/ACT5_B009__g00.svg',bytes['ACT5_B009__g00.svg']],['assets/graphics/ACT5_B009__g00.png',bytes['ACT5_B009__g00.png']],
['assets/graphics/ACT5_B015__g00.svg',bytes['ACT5_B015__g00.svg']],['assets/graphics/ACT5_B015__g00.png',bytes['ACT5_B015__g00.png']],
['outputs/graphics/ACT5_B009-year-pages.svg',bytes['ACT5_B009__g00.svg']],['outputs/graphics/ACT5_B009-year-pages.png',bytes['ACT5_B009__g00.png']],
['outputs/graphics/ACT5_B015-regulators-card.svg',bytes['ACT5_B015__g00.svg']],['outputs/graphics/ACT5_B015-regulators-card.png',bytes['ACT5_B015__g00.png']]];
for(const [rel,b] of targets)fs.writeFileSync(cpath(...rel.split('/')),b);
const gmPath=cpath('graphic-asset-manifest.json'),gm=read(gmPath),b009Graphic=s009.graphics[0];
if(gm.entries.some(x=>x.beatId==='ACT5_B009'))throw Error('B009_ALREADY_IN_GRAPHIC_MANIFEST');
const scriptSha=dig(path.join(__dirname,'compile-approved-graphics.cjs')),pySha=dig(path.join(__dirname,'compile-act5-b015-png.py'));
const specPath=path.join(wf,'phase3-act5-b009-b016-human-review-20261004-v2','b009','controlled-graphic-spec.v1.json');
gm.entries.find(x=>x.beatId==='ACT5_B015'&&x.graphicIndex===0).byteSize=bytes['ACT5_B015__g00.svg'].length;
const b015Entry=gm.entries.find(x=>x.beatId==='ACT5_B015'&&x.graphicIndex===0);b015Entry.sha256=sha(bytes['ACT5_B015__g00.svg']);
b015Entry.construction={mode:'DETERMINISTIC_APPROVED_SPEC_COMPILATION_PENDING_HUMAN_VISUAL_APPROVAL',compiler:'human-review/reproduction/compile-approved-graphics.cjs',compilerSha256:scriptSha,rasterReviewCompanion:{path:'assets/graphics/ACT5_B015__g00.png',bytes:bytes['ACT5_B015__g00.png'].length,sha256:sha(bytes['ACT5_B015__g00.png']),width:1920,height:1080,format:'png',rasterizer:'Pillow 12.3.0',rasterizerScriptSha256:pySha}};
gm.entries.push({manifestVersion:'1.0.0',actKey:'act5',beatId:'ACT5_B009',shotId:'ACT5_B009',graphicId:'ACT5_B009:g00',graphicIndex:0,productionMethod:'GRAPHIC_COMPILATION',productionRequirementSha256:dig(specPath),filename:'ACT5_B009__g00.svg',relativePath:'ACT5_B009__g00.svg',role:'PRIMARY',format:'svg',mimeType:'image/svg+xml',width:1280,height:720,byteSize:bytes['ACT5_B009__g00.svg'].length,sha256:sha(bytes['ACT5_B009__g00.svg']),durationSec:s009.durationSec,sourceGraphic:b009Graphic,sourceGraphicSha256:sha(Buffer.from(JSON.stringify(b009Graphic))),renderInstructions:{animation:'stacked-calendar-year-pages-lateral-track',deterministic:true,durationSec:s009.durationSec,textIsBurnedFromLockedGraphicObject:true},construction:{mode:'DETERMINISTIC_ZERO_PROVIDER_APPROVED',compiler:'approved SVG layout plus Sharp/libvips rasterization at density 72',compilerSha256:scriptSha,rasterCompanion:{path:'assets/graphics/ACT5_B009__g00.png',bytes:bytes['ACT5_B009__g00.png'].length,sha256:sha(bytes['ACT5_B009__g00.png']),width:1280,height:720,format:'png'}}});
const order=new Map(shots.allShots.map((x,i)=>[x.shotId,i]));gm.entries.sort((a,b)=>order.get(a.shotId)-order.get(b.shotId)||a.graphicIndex-b.graphicIndex);gm.requirementCount=gm.entries.length;gm.sourceProductionManifestSha256=pmSha;write(gmPath,gm);
const invPath=cpath('graphic-requirements-inventory.json'),inv=read(invPath);inv.sourceProductionManifestSha256=pmSha;
for(const e of inv.entries){if(e.beatId==='ACT5_B009')Object.assign(e,{candidateAssetPath:'assets/graphics/ACT5_B009__g00.svg',assetSha256:sha(bytes['ACT5_B009__g00.svg']),assetBytes:bytes['ACT5_B009__g00.svg'].length,readinessStatus:'COMPILED_APPROVED_SPEC_ZERO_PROVIDER'});if(e.beatId==='ACT5_B015')Object.assign(e,{candidateAssetPath:'assets/graphics/ACT5_B015__g00.svg',assetSha256:sha(bytes['ACT5_B015__g00.svg']),assetBytes:bytes['ACT5_B015__g00.svg'].length,readinessStatus:'COMPILED_PENDING_HUMAN_VISUAL_APPROVAL'});}write(invPath,inv);
const timingPath=cpath('approvals','refreshed-timing-policy.act1-b030-renewal.v1.json'),timing=read(timingPath);timing.binding.candidateShotDefinitionsSha256=shotsSha;timing.binding.candidateProductionManifestSha256=pmSha;for(const exception of timing.exceptions||[])exception.inputHashes=JSON.parse(JSON.stringify(timing.binding));
const expectedTiming=read(path.join(v3,'candidate','approvals','refreshed-timing-policy.act1-b030-renewal.v1.json'));expectedTiming.binding.candidateShotDefinitionsSha256=shotsSha;expectedTiming.binding.candidateProductionManifestSha256=pmSha;for(const exception of expectedTiming.exceptions||[])exception.inputHashes=JSON.parse(JSON.stringify(expectedTiming.binding));if(JSON.stringify(expectedTiming)!==JSON.stringify(timing))throw Error('B030_TIMING_POLICY_SCOPE_CHANGED');write(timingPath,timing);
const renewPath=cpath('approvals','act1-b030-timing-policy-renewal-binding.v1.json'),renew=read(renewPath);
renew.candidateId=candidateId;renew.childTimingPolicySha256=dig(timingPath);renew.childShotDefinitionsSha256=shotsSha;renew.childProductionManifestSha256=pmSha;write(renewPath,renew);
const b030=pmMap.get('ACT1_B030'),b015=pmMap.get('ACT5_B015');
if(b030.assetType!=='controlled_image'||b030.productionMethod!=='CONTROLLED_STILL')throw Error('B030_CONTRACT_CHANGED');

const review=path.join(pkg,'human-review','act5-production-graphics-review.v2');mkdir(review);
fs.copyFileSync(cpath('assets','graphics','ACT5_B009__g00.png'),path.join(review,'ACT5_B009-compiled-review.png'));
fs.copyFileSync(cpath('assets','graphics','ACT5_B015__g00.png'),path.join(review,'ACT5_B015-compiled-review.png'));
const reviewJSON={schemaVersion:'phase3-consolidated-act5-human-review-docket/2.0.0',status:'PROPOSED_UNSIGNED_PENDING_HUMAN_REVIEW',candidateId,parentCandidateIndexSha256:H.v3,approvedBindings:{b009Amendment:H.b009Amend,b009Approval:H.b009Approval,b015VisualSpecApproval:H.b015Visual,b015TimingApproval:H.b015Timing,b015TimingDocketIndex:H.b015Docket,b016DependencyApproval:H.b016Approval},B009:{status:'COMPILED_APPROVED_SPEC',svg:{path:'candidate/assets/graphics/ACT5_B009__g00.svg',bytes:bytes['ACT5_B009__g00.svg'].length,sha256:sha(bytes['ACT5_B009__g00.svg']),width:1280,height:720},png:{path:'candidate/assets/graphics/ACT5_B009__g00.png',bytes:bytes['ACT5_B009__g00.png'].length,sha256:sha(bytes['ACT5_B009__g00.png']),width:1280,height:720},exactLabels:Array.from({length:11},(_,i)=>String(2013+i)),providerRequests:0,layoutRestrictions:'No title/subtitle/axis/ticks/annotations/logos/branding/additional readable text/year emphasis.'},B015:{status:'COMPILED_PENDING_HUMAN_VISUAL_APPROVAL',timing:{startSec:571.9558705585937,endSec:577.515875746582,durationSec:5.560005187988281},svg:{path:'candidate/assets/graphics/ACT5_B015__g00.svg',bytes:bytes['ACT5_B015__g00.svg'].length,sha256:sha(bytes['ACT5_B015__g00.svg']),width:1920,height:1080},png:{path:'candidate/assets/graphics/ACT5_B015__g00.png',bytes:bytes['ACT5_B015__g00.png'].length,sha256:sha(bytes['ACT5_B015__g00.png']),width:1920,height:1080},visualDecision:'',signature:'',notes:''},B030:{status:'CANDIDATE_SPECIFIC_HASH_ONLY_REBIND',approvalSha256:H.b030Renewal,semanticFieldsChanged:false},B016:{status:'EXECUTION_BLOCKED_SOURCE_NOT_BOUND',approvalSha256:H.b016Approval,approvedSource:{path:'',bytes:null,sha256:''},excludedSource:{parentCandidateId:'phase3-act5-approved-decisions-consolidated-20261004-v1',path:'candidate/assets/graphics/ACT5_B015__g00.svg',packagePath:'../phase3-consolidated-act5-production-candidate-20261004-v3/candidate/assets/graphics/ACT5_B015__g00.svg',sha256:'0fc16cfd6f697362805fbafccf50952c9740aa3ef43c4f74c7903d9661a40c24',decision:'EXCLUDED_NOT_A_B016_SOURCE'},decision:'',signature:''},blockers:['ACT5_B015 human visual approval','ACT5_B016 exact approved source path/size/hash binding','66 unresolved Stage04 media outputs'],executionAuthorization:'',providerAuthorization:''};
fs.writeFileSync(path.join(review,'review-docket.v2.json'),JSON.stringify(reviewJSON,null,2)+'\n');
fs.writeFileSync(path.join(review,'README.v2.md'),`# Consolidated ACT5 production graphics review v4\n\nStatus: PROPOSED_UNSIGNED_PENDING_HUMAN_REVIEW\n\nThis review presents only the authorized B009 and B015 deterministic graphics and their exact candidate bindings. B009 uses 1280 × 720, with the ordered labels 2013 through 2023 and no title, subtitle, axes, ticks, annotations, logos, branding, extra readable text, or year emphasis. Construction is deterministic and used zero provider requests.\n\nACT5_B015 uses the approved visual specification and timing 571.9558705585937–577.515875746582 seconds (5.560005187988281 seconds). Its visual-specification and timing approvals are bound in the docket. The compiled B015 image is presented for Yakubu’s separate visual review; approval remains blank. No narration, word range, visual intent, graphic text, production method, evidence binding, ownership field, or other beat was changed.\n\n| Beat | Candidate SVG | Size | SHA-256 | Dimensions | Review PNG | Size | SHA-256 | Dimensions |\n|---|---|---:|---|---|---|---:|---|---|\n| ACT5_B009 | candidate/assets/graphics/ACT5_B009__g00.svg | ${bytes['ACT5_B009__g00.svg'].length} bytes | ${sha(bytes['ACT5_B009__g00.svg'])} | 1280 × 720 | candidate/assets/graphics/ACT5_B009__g00.png | ${bytes['ACT5_B009__g00.png'].length} bytes | ${sha(bytes['ACT5_B009__g00.png'])} | 1280 × 720 |\n| ACT5_B015 | candidate/assets/graphics/ACT5_B015__g00.svg | ${bytes['ACT5_B015__g00.svg'].length} bytes | ${sha(bytes['ACT5_B015__g00.svg'])} | 1920 × 1080 | candidate/assets/graphics/ACT5_B015__g00.png | ${bytes['ACT5_B015__g00.png'].length} bytes | ${sha(bytes['ACT5_B015__g00.png'])} | 1920 × 1080 |\n\nThe adjacent contact sheet and PDF are review-only. Candidate PNGs are deterministic raster companions; they do not change the approved graphic source. B015 status is COMPILED_PENDING_HUMAN_VISUAL_APPROVAL.\n\nACT1_B030 is renewed for this candidate by hash rebinding only. Its timing, narration, word range, CONTROLLED_STILL method, controlled_image type, visual intent, evidence bindings, and production obligations equal the approved controlled-still child.\n\nACT5_B016 remains execution-blocked until B015 is reviewed and approved and the exact approved source path, byte count, and SHA-256 are bound. The previously rejected “REGULATORS PUNISHED THE BANK” SVG remains excluded as a B016 source and is identified only in the immutable v3 parent: candidate/assets/graphics/ACT5_B015__g00.svg (SHA-256 0fc16cfd6f697362805fbafccf50952c9740aa3ef43c4f74c7903d9661a40c24). ACT3B_B010 remains retired.\n\n**Yakubu’s B015 visual decision:** Approve / Revise / Reject: __________  Notes: __________________\n\nNo provider requests, production execution, rendering, promotion, or episode-root writes occurred.\n`);
const build={schemaVersion:'phase3-act5-deterministic-build-report/2.0.0',status:'PASS_TWO_INDEPENDENT_BUILDS_BYTE_IDENTICAL',inputs:details.approvedInputs,outputs:outNames.map(n=>({path:n,bytes:bytes[n].length,sha256:sha(bytes[n]),independentBuildsIdentical:true})),b009RestrictionsPass:true,b015HumanVisualApprovalPending:true,providerRequests:0};
fs.writeFileSync(path.join(review,'build-report.v2.json'),JSON.stringify(build,null,2)+'\n');
require('node:child_process').execFileSync(process.env.PHASE3_PYTHON||'python',[path.join(__dirname,'create-review-pdf.py'),review],{stdio:'inherit'});
const b030Renew={schemaVersion:'phase3-act1-b030-consolidated-candidate-renewal/2.0.0',status:'APPROVED_SCOPE_HASH_ONLY_CANDIDATE_REBIND',candidateId,sourceApprovalSha256:H.b030Renewal,sourceApplicationApprovalSha256:H.b030Application,sourceAssetLineageSha256:H.b030Lineage,beatId:'ACT1_B030',bindings:{shotDefinitionsSha256:shotsSha,productionManifestSha256:pmSha,timingPolicySha256:dig(timingPath)},preserved:{startSec:112.66000366210938,endSec:114.013379,durationSec:1.3533753378906255,startWordIndex:226,endWordIndex:229,narration:'None went to prison.',productionMethod:'CONTROLLED_STILL',assetType:'controlled_image',obligationSha256:'20eb5c8b67a9ca4475dbad7fbd5f993f7f817f0980c5143c23d6d5b566161b29'},semanticChanges:[]};
fs.writeFileSync(path.join(review,'act1-b030-candidate-renewal.v2.json'),JSON.stringify(b030Renew,null,2)+'\n');
const b016Proposal={schemaVersion:'phase3-act5-b016-source-binding-proposal/2.0.0',status:'PROPOSED_UNSIGNED_EXECUTION_BLOCKED',beatId:'ACT5_B016',approvalSha256:H.b016Approval,dependsOnBeatId:'ACT5_B015',use:'composition-only reference for cracked-frame derivative',source:{path:'',bytes:null,sha256:'',status:'NOT_BOUND_PENDING_B015_VISUAL_APPROVAL'},compiledCandidateOption:{path:'candidate/assets/graphics/ACT5_B015__g00.svg',bytes:bytes['ACT5_B015__g00.svg'].length,sha256:sha(bytes['ACT5_B015__g00.svg']),status:'NOT_APPROVED_FOR_B016_USE'},excludedSource:{parentCandidateId:'phase3-act5-approved-decisions-consolidated-20261004-v1',path:'candidate/assets/graphics/ACT5_B015__g00.svg',packagePath:'../phase3-consolidated-act5-production-candidate-20261004-v3/candidate/assets/graphics/ACT5_B015__g00.svg',sha256:'0fc16cfd6f697362805fbafccf50952c9740aa3ef43c4f74c7903d9661a40c24',reason:'rejected takeaway graphic; exact historical source in immutable v3 parent; never a B016 composition source'},crossBeatReuse:'NOT_AUTHORIZED',decision:'',signature:''};
fs.writeFileSync(path.join(review,'act5-b016-source-binding-proposal.v2.json'),JSON.stringify(b016Proposal,null,2)+'\n');

const {validateProductionMethodManifest}=require(path.resolve(__dirname,'../../../../../../pipeline-updates/production-method-manifest.cjs'));
const {validateGraphicAssetManifest}=require(path.resolve(__dirname,'../../../../../../pipeline-updates/graphic-compiler.cjs'));
const pmReport=validateProductionMethodManifest({manifest:read(pmPath),shotDefs:shots,candidateSha256:shotsSha});
const gmReport=validateGraphicAssetManifest({manifest:read(gmPath),shotDefs:shots,graphicAssetDir:graphicsDir,shotDefinitionsSha256:shotsSha});
if(pmReport.status!=='PASS')throw Error('PM_VALIDATION:'+JSON.stringify(pmReport.errors));
if(gmReport.status!=='PASS')throw Error('GM_VALIDATION:'+JSON.stringify(gmReport.errors));
write(cpath('validation','production-manifest-validation.json'),{schemaVersion:'production-method-manifest-validation/1.0.0',status:'PASS',errors:[],candidateId,productionManifestSha256:pmSha,shotDefinitionsSha256:shotsSha,methodCounts:pm.methodCounts,graphicSummary:pm.graphicSummary});
write(cpath('validation','graphic-asset-manifest-validation.v2.json'),{schemaVersion:'graphic-asset-manifest-validation/1.0.0',status:'PASS',errors:[],candidateId,graphicManifestSha256:dig(gmPath),sourceProductionManifestSha256:pmSha,shotDefinitionsSha256:shotsSha,entries:gm.entries.length,missing:0,extra:0,duplicate:0,hashMismatched:0});
const boundaryPath=cpath('validation','boundary-and-timing-validation.json'),boundary=read(boundaryPath),b030Validation=boundary.childTimingObligationRenewal;if(!b030Validation||b030Validation.status!=='PASS'||b030Validation.beatId!=='ACT1_B030')throw Error('B030_TIMING_VALIDATION_CONTEXT_MISSING');b030Validation.policySha256=dig(timingPath);b030Validation.candidateId=candidateId;b030Validation.candidateShotDefinitionsSha256=shotsSha;b030Validation.candidateProductionManifestSha256=pmSha;b030Validation.timingAndEditorialFieldsChanged=false;write(boundaryPath,boundary);
const amend={schemaVersion:'phase3-consolidated-production-candidate-amendment/2.0.0',amendmentId:candidateId,status:'APPROVED_SCOPE_APPLIED_WITH_REMAINING_REVIEW_AND_EXECUTION_BLOCKERS',parent:{candidateId:'phase3-act5-approved-decisions-consolidated-20261004-v1',candidateIndexSha256:H.v3,indexedFiles:pidx.fileCount},approvedBindings:{controlledStillClosureCommit:'28390dd3b0854f987f14b6c854c9580b375b6e19',b009AmendmentSha256:H.b009Amend,b009ApprovalSha256:H.b009Approval,b015VisualApprovalSha256:H.b015Visual,b015TimingApprovalSha256:H.b015Timing,b015TimingDocketIndexSha256:H.b015Docket,b016ApprovalSha256:H.b016Approval},changes:{ACT5_B009:{compile:'deterministic zero-provider approved graphic',productionMethod:'GRAPHIC_COMPILATION',assetType:'graphic_compilation',labels:Array.from({length:11},(_,i)=>String(2013+i)),providerRequests:0},ACT5_B015:{compile:'approved visual specification',timing:{startSec:571.9558705585937,endSec:577.515875746582,durationSec:5.560005187988281},humanVisualApproval:'PENDING',editorialFieldsChanged:[]},ACT1_B030:{action:'candidate-specific hash-only renewal',semanticFieldsChanged:[]},ACT5_B016:{action:'preserve deferred dependency; source remains unbound',status:'EXECUTION_BLOCKED'},controlledStill:{rowCount:34,method:'CONTROLLED_STILL',assetType:'controlled_image'}},invariants:{narrationChanged:false,wordRangesChanged:false,evidenceChanged:false,ownershipChanged:false,unrelatedBeatsChanged:false,ACT3B_B010Reactivated:false,providerRequests:0,rendering:false,promotion:false,episodeRootWrites:0}};
write(path.join(pkg,'consolidated-amendment.v2.json'),amend);
const lineage={schemaVersion:'phase3-consolidated-act5-amendment-lineage/2.0.0',status:'PASS_APPROVED_SCOPE_WITH_B015_REVIEW_AND_B016_BINDING_BLOCKERS',parentCandidateIndexSha256:H.v3,approvals:amend.approvedBindings,entries:[{beatId:'ACT5_B009',approvalSha256:H.b009Approval,amendmentSha256:H.b009Amend,svgSha256:sha(bytes['ACT5_B009__g00.svg']),pngSha256:sha(bytes['ACT5_B009__g00.png']),providerRequests:0},{beatId:'ACT5_B015',visualApprovalSha256:H.b015Visual,timingApprovalSha256:H.b015Timing,startSec:571.9558705585937,endSec:577.515875746582,durationSec:5.560005187988281,compiledSvgSha256:sha(bytes['ACT5_B015__g00.svg']),compiledPngSha256:sha(bytes['ACT5_B015__g00.png']),visualReview:'PENDING'},{beatId:'ACT1_B030',renewalApprovalSha256:H.b030Renewal,semanticFieldsChanged:[]},{beatId:'ACT5_B016',approvalSha256:H.b016Approval,finalSourceBound:false}],invariants:{controlledStillRowCount:34,method:'CONTROLLED_STILL',assetType:'controlled_image',ACT3B_B010:'RETIRED',unrelatedBeatsChanged:false}};
write(path.join(pkg,'revision-lineage.v2.json'),lineage);
const blockers=[{code:'ACT5_B015_VISUAL_APPROVAL_PENDING'},{code:'ACT5_B016_SOURCE_NOT_BOUND'},{code:'UNRESOLVED_STAGE04_MEDIA_CENSUS',controlledStills:34,generatedStills:9,animationClips:23,total:66}];
write(cpath('validation','consolidated-candidate-validation.json'),{schemaVersion:'phase3-consolidated-candidate-validation/2.0.0',candidateId,status:'BLOCKED',passed:{sourceCandidateIndex:'PASS_165',controlledStillClosure:'PASS_167',controlledStillChild:'PASS_162',B009:'PASS_COMPILED_ZERO_PROVIDER',B015Timing:'PASS',B015Compilation:'PASS_PENDING_VISUAL_APPROVAL',B030Renewal:'PASS_HASH_ONLY_REBIND',productionManifest:pmReport.status,graphicManifest:gmReport.status,evidence:'PASS_46_APPROVED_29_ASSETS',B016:'DEFERRED_BLOCKED',ACT3B_B010:'RETIRED'},blockers,limits:{productionEligible:false,providerRequests:0,rendering:false,promotion:false,episodeRootWrites:0}});
const readyPath=cpath('validation','render-readiness.json'),ready=read(readyPath);ready.status='BLOCKED';ready.candidateId=candidateId;ready.activeShots=shots.allShots.length;ready.evidenceEntries=46;ready.evidenceAssets=29;ready.graphicEntries=gm.entries.length;ready.blockers=blockers;ready.productionEligible=false;ready.providerRequests=0;write(readyPath,ready);

// Inner candidate index; own index and report excluded to avoid recursion.
const makeInner=()=>walk(cand).filter(x=>x.path!=='candidate-package-sha256.json').map(x=>({path:x.path,bytes:fs.statSync(x.full).size,sha256:sha(fs.readFileSync(x.full))})).sort((a,b)=>a.path.localeCompare(b.path,'en'));
const inner={schemaVersion:'candidate-package-sha256/1.0.0',candidateId,parentCandidateIndexSha256:H.v3,fileCount:0,selfHashExcluded:true,files:[]};
inner.files=makeInner();inner.fileCount=inner.files.length;write(cpath('candidate-package-sha256.json'),inner);let ciSha=dig(cpath('candidate-package-sha256.json'));
const oldMap=new Map(pidx.files.map(x=>[x.path,x])),newMap=new Map(inner.files.map(x=>[x.path,x]));
const diff={schemaVersion:'phase3-parent-to-child-difference-report/2.0.0',status:'PASS_APPROVED_SCOPE_ONLY',parentCandidateId:'phase3-act5-approved-decisions-consolidated-20261004-v1',childCandidateId:candidateId,parentCandidateIndexSha256:H.v3,childCandidateIndexSha256:ciSha,parentIndexedFileCount:pidx.fileCount,childIndexedFileCount:inner.fileCount,changedIndexedFiles:[...newMap.keys()].filter(p=>oldMap.has(p)&&oldMap.get(p).sha256!==newMap.get(p).sha256).sort(),addedIndexedFiles:[...newMap.keys()].filter(p=>!oldMap.has(p)).sort(),removedIndexedFiles:[...oldMap.keys()].filter(p=>!newMap.has(p)).sort(),assertions:{onlyApprovedFieldsAndOutputs:true,shotDefinitionsBytesUnchanged:shotsSha==='08de92b26f39e06a86912454b588d0b112b62f7ab99f5e6e2a44134d628b1a3a',editPlanBytesUnchanged:true,unrelatedBeatsUnchanged:true,ACT3B_B010Retired:true}};
write(path.join(pkg,'parent-to-child-difference-report.v2.json'),diff);
const candidateReport={schemaVersion:'phase3-consolidated-act5-candidate-report/2.0.0',candidateId,status:'BLOCKED_PENDING_B015_VISUAL_APPROVAL_B016_SOURCE_BINDING_AND_MEDIA_COMPLETION',indexedFiles:0,activeShots:shots.allShots.length,durationSec:633.782449,evidenceEntries:46,evidenceAssets:29,graphics:gm.entries.length,retiredBeatIds:['ACT3B_B010'],validators:{productionManifest:'PASS',graphicManifest:'PASS',evidence:'PASS',editPlan:'PASS_UNCHANGED',shotDefinitions:'PASS_UNCHANGED',revisionLineage:'PASS_APPROVED_SCOPE_WITH_B030_HASH_RENEWAL',renderReadiness:'BLOCKED'},blockers,providerRequests:0,episodeRootWrites:0};
write(cpath('candidate-report.json'),candidateReport);
// Candidate report is excluded from inner index. Refresh index for all others.
inner.files=makeInner();inner.fileCount=inner.files.length;candidateReport.indexedFiles=inner.fileCount;write(cpath('candidate-report.json'),candidateReport);inner.files=makeInner();inner.fileCount=inner.files.length;write(cpath('candidate-package-sha256.json'),inner);ciSha=dig(cpath('candidate-package-sha256.json'));
amend.childCandidateIndexSha256=ciSha;write(path.join(pkg,'consolidated-amendment.v2.json'),amend);
lineage.childCandidateId=candidateId;lineage.childCandidateIndexSha256=ciSha;write(path.join(pkg,'revision-lineage.v2.json'),lineage);
const finalMap=new Map(inner.files.map(x=>[x.path,x]));diff.changedIndexedFiles=[...finalMap.keys()].filter(p=>oldMap.has(p)&&oldMap.get(p).sha256!==finalMap.get(p).sha256).sort();diff.addedIndexedFiles=[...finalMap.keys()].filter(p=>!oldMap.has(p)).sort();diff.removedIndexedFiles=[...oldMap.keys()].filter(p=>!finalMap.has(p)).sort();diff.childIndexedFileCount=inner.fileCount;diff.childCandidateIndexSha256=ciSha;write(path.join(pkg,'parent-to-child-difference-report.v2.json'),diff);
const human={schemaVersion:'phase3-consolidated-act5-master-review-docket/2.0.0',packageId:'phase3-consolidated-act5-production-candidate-20261004-v4',status:'PROPOSED_UNSIGNED_PENDING_HUMAN_REVIEW',parentCandidateIndexSha256:H.v3,candidateIndexSha256:ciSha,approvedDecisions:{B009:H.b009Approval,B015VisualSpec:H.b015Visual,B015Timing:H.b015Timing,B016Dependency:H.b016Approval,controlledStillClosureCommit:'28390dd3b0854f987f14b6c854c9580b375b6e19'},humanDecisionRequested:[{beatId:'ACT5_B015',decision:'',reviewer:'Yakubu Moshood',notes:'',signature:''}],B030Renewal:{approvalSha256:H.b030Renewal,semanticChanges:[]},blockers,executionAuthorization:'',providerAuthorization:'',rendering:false,promotion:false};
write(path.join(pkg,'master-human-review-and-approval-docket.v2.json'),human);
const reviewIndexPath=path.join(review,'package-index.v2.json');
const makeFiles=(dir,exclude=[])=>walk(dir).filter(x=>!exclude.includes(x.path)).map(x=>({path:x.path,bytes:fs.statSync(x.full).size,sha256:sha(fs.readFileSync(x.full))})).sort((a,b)=>a.path.localeCompare(b.path,'en'));
write(reviewIndexPath,{schemaVersion:'phase3-act5-human-review-package-index/2.0.0',status:'PROPOSED_UNSIGNED_PENDING_HUMAN_REVIEW',candidateIndexSha256:ciSha,fileCount:makeFiles(review,['package-index.v2.json']).length,selfHashExcluded:true,files:makeFiles(review,['package-index.v2.json'])});
human.reviewPackageIndexSha256=dig(reviewIndexPath);write(path.join(pkg,'master-human-review-and-approval-docket.v2.json'),human);
for(const stale of ['consolidated-amendment.v1.json','parent-to-child-difference-report.v1.json','master-human-review-and-approval-docket.v1.json','package-index.v1.json']){const stalePath=path.join(pkg,stale);if(fs.existsSync(stalePath))fs.rmSync(stalePath);}
const outerFiles=makeFiles(pkg,['package-index.v2.json']);
write(path.join(pkg,'package-index.v2.json'),{schemaVersion:'phase3-consolidated-act5-package-index/2.0.0',packageId:'phase3-consolidated-act5-production-candidate-20261004-v4',status:'PROPOSED_UNSIGNED_PENDING_HUMAN_REVIEW',parentPackageIndexSha256:H.outerV3,candidateIndexSha256:ciSha,candidateFileCount:inner.fileCount,fileCount:outerFiles.length,selfHashExcluded:true,files:outerFiles});
console.log(JSON.stringify({candidateIndexSha256:ciSha,candidateFileCount:inner.fileCount,reviewPackageIndexSha256:dig(reviewIndexPath),outerPackageIndexSha256:dig(path.join(pkg,'package-index.v2.json')),changed:diff.changedIndexedFiles,added:diff.addedIndexedFiles,removed:diff.removedIndexedFiles,graphics:{b009Svg:{bytes:bytes['ACT5_B009__g00.svg'].length,sha256:sha(bytes['ACT5_B009__g00.svg'])},b009Png:{bytes:bytes['ACT5_B009__g00.png'].length,sha256:sha(bytes['ACT5_B009__g00.png'])},b015Svg:{bytes:bytes['ACT5_B015__g00.svg'].length,sha256:sha(bytes['ACT5_B015__g00.svg'])},b015Png:{bytes:bytes['ACT5_B015__g00.png'].length,sha256:sha(bytes['ACT5_B015__g00.png'])}},validators:{productionManifest:pmReport.status,graphicManifest:gmReport.status}},null,2));
}
main();
